---
title: "A UN Report on the relationship between GDP and Emmissions"
author: "Diana"
date: "2023-01-18"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages, include=FALSE}
library(tidyverse)
library(knitr)
```

This report was prepared for the UN blah blah blah...

```{r read-data, include=FALSE}
gapminder_1997 <- read_csv("data/gapminder_1997.csv")
```

```{r gdp-lifeexp-1997-plot, echo=FALSE}
#make plot of GDP vs life Exp
ggplot(data=gapminder_1997)+
  aes(x=gdpPercap,y=lifeExp)+
  labs(x="GDP per capita",y="Life Expectancy (years)",title="GDP vs Life Expectancy 1997")+
  geom_point()
```

```{r, basic country stats}
nCountries <- 
  gapminder_1997%>%
  select(country)%>%
  n_distinct()

minGDP <-
  gapminder_1997%>%
  summarise(round(min(gdpPercap)))%>%
  pull()

```

The number of countries in the dataset is `r nCountries`. 
The minimum GDP id `r minGDP`.

```{r, Table}
gapminder_1997 %>%
  filter(continent == "Oceania")%>%
  kable()
#kable function prints table
```

